### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jbibla**
Just a lil' typo. 🙃

### CODE REVIEW

**Review by HenryYYang — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for HenryYYang @ 2021-07-23 20:11:59 UTC
User must have write permissions to review

**Review by HenryYYang — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for HenryYYang @ 2021-07-26 18:12:47 UTC
User must have write permissions to review

**Review by HenryYYang — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for HenryYYang @ 2021-07-27 17:14:22 UTC
User must have write permissions to review

**Review by HenryYYang — APPROVED** [review]

**Comment by shrimalmadhur** [comment]
> Just a lil' typo. 🙃

@jbibla would you mind rebasing it and pushing the change. We had some build issue which we fixed and you need to rebase this branch. Thanks

**Comment by shrimalmadhur** [comment]
will be fixed by #82

**Comment by shrimalmadhur** [comment]
@jbibla I am reopening this PR since we are closing #82 . Can you rebase this an push again so that build gets cleared

**Review by jeska805KILLA — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for jeska805KILLA @ 2022-03-18 09:57:25 UTC
User must have write permissions to review

**Pull request closed without merging**
